'use client'

import { useState } from 'react'
import { XMarkIcon } from '@heroicons/react/24/outline'

// Define element categories and their colors
type ElementCategory = 
  | 'Alkali Metal'
  | 'Alkaline Earth Metal'
  | 'Transition Metal'
  | 'Post-transition Metal'
  | 'Metalloid'
  | 'Nonmetal'
  | 'Noble Gas'
  | 'Lanthanide'
  | 'Actinide'

const categories: Record<ElementCategory, string> = {
  'Alkali Metal': 'bg-cyan-100 hover:bg-cyan-200',
  'Alkaline Earth Metal': 'bg-red-100 hover:bg-red-200',
  'Transition Metal': 'bg-purple-100 hover:bg-purple-200',
  'Post-transition Metal': 'bg-green-100 hover:bg-green-200',
  'Metalloid': 'bg-amber-100 hover:bg-amber-200',
  'Nonmetal': 'bg-blue-100 hover:bg-blue-200',
  'Noble Gas': 'bg-rose-100 hover:bg-rose-200',
  'Lanthanide': 'bg-blue-100 hover:bg-blue-200',
  'Actinide': 'bg-orange-100 hover:bg-orange-200',
}

interface Element {
  atomicNumber: number
  symbol: string
  name: string
  atomicMass: string
  category: ElementCategory
  electronConfiguration: string
  electronegativity: number
  atomicRadius: number
  ionizationEnergy: number
  density: number
  meltingPoint: number
  boilingPoint: number
  discoveredBy: string
  yearDiscovered: number
  description: string
  period: number
  group: number
}

// Define the periodic table data
const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: '1.008',
    category: 'Nonmetal',
    electronConfiguration: '1s¹',
    electronegativity: 2.2,
    atomicRadius: 37,
    ionizationEnergy: 1312,
    density: 0.0000899,
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    discoveredBy: 'Henry Cavendish',
    yearDiscovered: 1766,
    description: 'Hydrogen is the lightest and most abundant chemical element in the Universe. It is essential for life and is present in water and all organic compounds.',
    period: 1,
    group: 1,
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: '4.003',
    category: 'Noble Gas',
    electronConfiguration: '1s²',
    electronegativity: 0,
    atomicRadius: 32,
    ionizationEnergy: 2372,
    density: 0.0001785,
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    discoveredBy: 'Pierre Janssen',
    yearDiscovered: 1868,
    description: 'Helium is the second lightest and second most abundant element in the observable universe. It is used in cryogenics, deep-sea breathing systems, and party balloons.',
    period: 1,
    group: 2,
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: '6.941',
    category: 'Alkali Metal',
    electronConfiguration: '[He]2s¹',
    electronegativity: 0.98,
    atomicRadius: 134,
    ionizationEnergy: 520,
    density: 0.534,
    meltingPoint: 180.54,
    boilingPoint: 1342,
    discoveredBy: 'Johan August Arfwedson',
    yearDiscovered: 1817,
    description: 'Lithium is a soft, silvery-white alkali metal. It is used in rechargeable batteries and in the treatment of bipolar disorder.',
    period: 2,
    group: 1,
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: '9.012',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[He]2s²',
    electronegativity: 1.57,
    atomicRadius: 90,
    ionizationEnergy: 899,
    density: 1.85,
    meltingPoint: 1287,
    boilingPoint: 2470,
    discoveredBy: 'Louis Nicolas Vauquelin',
    yearDiscovered: 1797,
    description: 'Beryllium is a relatively hard, grayish metal. It is used in aerospace components and X-ray machines.',
    period: 2,
    group: 2,
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: '10.811',
    category: 'Metalloid',
    electronConfiguration: '[He]2s²2p¹',
    electronegativity: 2.04,
    atomicRadius: 82,
    ionizationEnergy: 800,
    density: 2.34,
    meltingPoint: 2075,
    boilingPoint: 4000,
    discoveredBy: 'Joseph Louis Gay-Lussac',
    yearDiscovered: 1808,
    description: 'Boron is a semiconductor with properties between metals and non-metals. It is used in fiberglass and as a neutron absorber in nuclear reactors.',
    period: 2,
    group: 3,
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: '12.011',
    category: 'Nonmetal',
    electronConfiguration: '[He]2s²2p²',
    electronegativity: 2.55,
    atomicRadius: 77,
    ionizationEnergy: 1086,
    density: 2.267,
    meltingPoint: 3550,
    boilingPoint: 4827,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -3750,
    description: 'Carbon is the basis for all known life forms. It exists in several forms including diamond and graphite, and is found in all organic compounds.',
    period: 2,
    group: 4,
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: '14.007',
    category: 'Nonmetal',
    electronConfiguration: '[He]2s²2p³',
    electronegativity: 3.04,
    atomicRadius: 75,
    ionizationEnergy: 1402,
    density: 0.001251,
    meltingPoint: -210,
    boilingPoint: -195.79,
    discoveredBy: 'Daniel Rutherford',
    yearDiscovered: 1772,
    description: 'Nitrogen is a colorless, odorless gas that makes up about 78% of Earth\'s atmosphere. It is essential for life and is used in fertilizers.',
    period: 2,
    group: 5,
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: '15.999',
    category: 'Nonmetal',
    electronConfiguration: '[He]2s²2p⁴',
    electronegativity: 3.44,
    atomicRadius: 73,
    ionizationEnergy: 1314,
    density: 0.001429,
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1772,
    description: 'Oxygen is essential for most life forms on Earth. It makes up about 21% of Earth\'s atmosphere and is used in respiration and combustion.',
    period: 2,
    group: 6,
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: '18.998',
    category: 'Nonmetal',
    electronConfiguration: '[He]2s²2p⁵',
    electronegativity: 3.98,
    atomicRadius: 71,
    ionizationEnergy: 1681,
    density: 0.001696,
    meltingPoint: -219.67,
    boilingPoint: -188.12,
    discoveredBy: 'Henri Moissan',
    yearDiscovered: 1886,
    description: 'Fluorine is the most reactive and electronegative of all elements. It is used in the production of many fluoride compounds.',
    period: 2,
    group: 17,
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: '20.180',
    category: 'Noble Gas',
    electronConfiguration: '[He]2s²2p⁶',
    electronegativity: 0,
    atomicRadius: 69,
    ionizationEnergy: 2081,
    density: 0.0009,
    meltingPoint: -248.59,
    boilingPoint: -246.08,
    discoveredBy: 'William Ramsay',
    yearDiscovered: 1898,
    description: 'Neon is a noble gas used in neon signs and lasers. It gives off a distinctive reddish-orange glow when used in gas-discharge lamps.',
    period: 2,
    group: 18,
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: '22.990',
    category: 'Alkali Metal',
    electronConfiguration: '[Ne]3s¹',
    electronegativity: 0.93,
    atomicRadius: 154,
    ionizationEnergy: 496,
    density: 0.971,
    meltingPoint: 97.72,
    boilingPoint: 883,
    discoveredBy: 'Humphry Davy',
    yearDiscovered: 1807,
    description: 'Sodium is a soft, silvery-white metal that is highly reactive. It is essential for life and is present in many minerals.',
    period: 3,
    group: 1,
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: '24.305',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[Ne]3s²',
    electronegativity: 1.31,
    atomicRadius: 130,
    ionizationEnergy: 738,
    density: 1.738,
    meltingPoint: 650,
    boilingPoint: 1090,
    discoveredBy: 'Joseph Black',
    yearDiscovered: 1755,
    description: 'Magnesium is a lightweight, silvery-white metal. It is essential for life and is used in alloys and pyrotechnics.',
    period: 3,
    group: 2,
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminium',
    atomicMass: '26.982',
    category: 'Post-transition Metal',
    electronConfiguration: '[Ne]3s²3p¹',
    electronegativity: 1.61,
    atomicRadius: 118,
    ionizationEnergy: 578,
    density: 2.7,
    meltingPoint: 660.32,
    boilingPoint: 2519,
    discoveredBy: 'Hans Christian Oersted',
    yearDiscovered: 1825,
    description: 'Aluminium is a lightweight, silvery-white metal. It is the most abundant metal in Earth\'s crust and is used in various applications.',
    period: 3,
    group: 13,
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: '28.085',
    category: 'Metalloid',
    electronConfiguration: '[Ne]3s²3p²',
    electronegativity: 1.90,
    atomicRadius: 111,
    ionizationEnergy: 787,
    density: 2.33,
    meltingPoint: 1414,
    boilingPoint: 3265,
    discoveredBy: 'Jöns Jacob Berzelius',
    yearDiscovered: 1824,
    description: 'Silicon is a metalloid essential for the electronics industry. It is the second most abundant element in Earth\'s crust.',
    period: 3,
    group: 14,
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: '30.974',
    category: 'Nonmetal',
    electronConfiguration: '[Ne]3s²3p³',
    electronegativity: 2.19,
    atomicRadius: 106,
    ionizationEnergy: 1012,
    density: 1.82,
    meltingPoint: 44.2,
    boilingPoint: 280.5,
    discoveredBy: 'Hennig Brand',
    yearDiscovered: 1669,
    description: 'Phosphorus is essential for life and is used in fertilizers. It exists in several forms, including white, red, and black phosphorus.',
    period: 3,
    group: 15,
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: '32.065',
    category: 'Nonmetal',
    electronConfiguration: '[Ne]3s²3p⁴',
    electronegativity: 2.58,
    atomicRadius: 102,
    ionizationEnergy: 1000,
    density: 2.07,
    meltingPoint: 115.21,
    boilingPoint: 444.72,
    discoveredBy: 'Ancient civilizations',
    yearDiscovered: -2000,
    description: 'Sulfur is a yellow nonmetal used in many industrial processes. It is essential for life and is found in many minerals.',
    period: 3,
    group: 16,
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: '35.453',
    category: 'Nonmetal',
    electronConfiguration: '[Ne]3s²3p⁵',
    electronegativity: 3.16,
    atomicRadius: 99,
    ionizationEnergy: 1251,
    density: 0.003214,
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1774,
    description: 'Chlorine is a yellow-green gas that is highly reactive. It is used in water treatment and in the production of many compounds.',
    period: 3,
    group: 17,
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: '39.948',
    category: 'Noble Gas',
    electronConfiguration: '[Ne]3s²3p⁶',
    electronegativity: 0,
    atomicRadius: 97,
    ionizationEnergy: 1521,
    density: 0.001784,
    meltingPoint: -189.35,
    boilingPoint: -185.85,
    discoveredBy: 'Lord Rayleigh and William Ramsay',
    yearDiscovered: 1894,
    description: 'Argon is a noble gas used in lighting and welding. It makes up about 1% of Earth\'s atmosphere.',
    period: 3,
    group: 18,
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: '39.098',
    category: 'Alkali Metal',
    electronConfiguration: '[Ar]4s¹',
    electronegativity: 0.82,
    atomicRadius: 196,
    ionizationEnergy: 419,
    density: 0.862,
    meltingPoint: 63.38,
    boilingPoint: 759,
    discoveredBy: 'Humphry Davy',
    yearDiscovered: 1807,
    description: 'Potassium is a soft, silvery-white alkali metal. It is essential for life and is used in fertilizers.',
    period: 4,
    group: 1,
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: '40.078',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[Ar]4s²',
    electronegativity: 1.00,
    atomicRadius: 174,
    ionizationEnergy: 590,
    density: 1.54,
    meltingPoint: 842,
    boilingPoint: 1484,
    discoveredBy: 'Humphry Davy',
    yearDiscovered: 1808,
    description: 'Calcium is essential for living organisms, particularly in bone formation. It is the fifth most abundant element in Earth\'s crust.',
    period: 4,
    group: 2,
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: '44.956',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d¹4s²',
    electronegativity: 1.36,
    atomicRadius: 144,
    ionizationEnergy: 633,
    density: 2.989,
    meltingPoint: 1541,
    boilingPoint: 2830,
    discoveredBy: 'Lars Fredrik Nilson',
    yearDiscovered: 1879,
    description: 'Scandium is a silvery-white metallic transition metal. It is used in aerospace components and sports equipment.',
    period: 4,
    group: 3,
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: '47.867',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d²4s²',
    electronegativity: 1.54,
    atomicRadius: 136,
    ionizationEnergy: 659,
    density: 4.54,
    meltingPoint: 1668,
    boilingPoint: 3287,
    discoveredBy: 'William Gregor',
    yearDiscovered: 1791,
    description: 'Titanium is a strong, lightweight metal used in aerospace and medical implants. It is resistant to corrosion.',
    period: 4,
    group: 4,
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: '50.942',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d³4s²',
    electronegativity: 1.63,
    atomicRadius: 125,
    ionizationEnergy: 651,
    density: 6.11,
    meltingPoint: 1910,
    boilingPoint: 3407,
    discoveredBy: 'Andrés Manuel del Río',
    yearDiscovered: 1801,
    description: 'Vanadium is a hard, silvery-gray metal used primarily in alloys. It is essential for some species.',
    period: 4,
    group: 5,
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: '51.996',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d⁵4s¹',
    electronegativity: 1.66,
    atomicRadius: 127,
    ionizationEnergy: 653,
    density: 7.15,
    meltingPoint: 1907,
    boilingPoint: 2671,
    discoveredBy: 'Louis Nicolas Vauquelin',
    yearDiscovered: 1797,
    description: 'Chromium is a steely-gray metal used in stainless steel and chrome plating. It is essential for human nutrition.',
    period: 4,
    group: 6,
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: '54.938',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d⁵4s²',
    electronegativity: 1.55,
    atomicRadius: 139,
    ionizationEnergy: 717,
    density: 7.44,
    meltingPoint: 1246,
    boilingPoint: 2061,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1774,
    description: 'Manganese is a silvery-gray metal used in steel production. It is essential for life and is found in many minerals.',
    period: 4,
    group: 7,
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: '55.845',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d⁶4s²',
    electronegativity: 1.83,
    atomicRadius: 125,
    ionizationEnergy: 762,
    density: 7.874,
    meltingPoint: 1538,
    boilingPoint: 2862,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -3500,
    description: 'Iron is the most widely used metal and is essential for life. It is the main component of steel and Earth\'s core.',
    period: 4,
    group: 8,
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: '58.933',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d⁷4s²',
    electronegativity: 1.88,
    atomicRadius: 126,
    ionizationEnergy: 760,
    density: 8.86,
    meltingPoint: 1495,
    boilingPoint: 2927,
    discoveredBy: 'Georg Brandt',
    yearDiscovered: 1735,
    description: 'Cobalt is a hard, lustrous, silver-blue metal. It is used in magnets and high-strength alloys.',
    period: 4,
    group: 9,
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: '58.693',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d⁸4s²',
    electronegativity: 1.91,
    atomicRadius: 124,
    ionizationEnergy: 737,
    density: 8.912,
    meltingPoint: 1455,
    boilingPoint: 2913,
    discoveredBy: 'Axel Fredrik Cronstedt',
    yearDiscovered: 1751,
    description: 'Nickel is a silvery-white metal used in stainless steel and batteries. It is resistant to corrosion.',
    period: 4,
    group: 10,
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: '63.546',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d¹⁰4s¹',
    electronegativity: 1.90,
    atomicRadius: 128,
    ionizationEnergy: 746,
    density: 8.96,
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -8000,
    description: 'Copper is a reddish metal that is an excellent conductor of electricity. It has been used by humans for thousands of years.',
    period: 4,
    group: 11,
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: '65.38',
    category: 'Transition Metal',
    electronConfiguration: '[Ar]3d¹⁰4s²',
    electronegativity: 1.65,
    atomicRadius: 134,
    ionizationEnergy: 906,
    density: 7.134,
    meltingPoint: 419.53,
    boilingPoint: 907,
    discoveredBy: 'Indian metallurgists',
    yearDiscovered: -1000,
    description: 'Zinc is a bluish-white metal used in galvanization and batteries. It is essential for life and found in many enzymes.',
    period: 4,
    group: 12,
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: '69.723',
    category: 'Post-transition Metal',
    electronConfiguration: '[Ar]3d¹⁰4s²4p¹',
    electronegativity: 1.81,
    atomicRadius: 135,
    ionizationEnergy: 579,
    density: 5.907,
    meltingPoint: 29.76,
    boilingPoint: 2204,
    discoveredBy: 'Paul-Émile Lecoq de Boisbaudran',
    yearDiscovered: 1875,
    description: 'Gallium is a soft, silvery metal that melts near room temperature. It is used in semiconductors and electronics.',
    period: 4,
    group: 13,
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: '72.630',
    category: 'Metalloid',
    electronConfiguration: '[Ar]3d¹⁰4s²4p²',
    electronegativity: 2.01,
    atomicRadius: 122,
    ionizationEnergy: 762,
    density: 5.323,
    meltingPoint: 938.25,
    boilingPoint: 2820,
    discoveredBy: 'Clemens Winkler',
    yearDiscovered: 1886,
    description: 'Germanium is a lustrous, hard, grayish-white metalloid. It is used in fiber optics and electronics.',
    period: 4,
    group: 14,
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: '74.922',
    category: 'Metalloid',
    electronConfiguration: '[Ar]3d¹⁰4s²4p³',
    electronegativity: 2.18,
    atomicRadius: 119,
    ionizationEnergy: 947,
    density: 5.776,
    meltingPoint: 817,
    boilingPoint: 614,
    discoveredBy: 'Ancient Egyptians',
    yearDiscovered: -2500,
    description: 'Arsenic is a metalloid that can be toxic. It is used in pesticides and some semiconductors.',
    period: 4,
    group: 15,
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: '78.971',
    category: 'Nonmetal',
    electronConfiguration: '[Ar]3d¹⁰4s²4p⁴',
    electronegativity: 2.55,
    atomicRadius: 120,
    ionizationEnergy: 941,
    density: 4.809,
    meltingPoint: 221,
    boilingPoint: 685,
    discoveredBy: 'Jöns Jacob Berzelius',
    yearDiscovered: 1817,
    description: 'Selenium is a nonmetal with properties similar to sulfur. It is used in electronics and supplements.',
    period: 4,
    group: 16,
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: '79.904',
    category: 'Nonmetal',
    electronConfiguration: '[Ar]3d¹⁰4s²4p⁵',
    electronegativity: 2.96,
    atomicRadius: 120,
    ionizationEnergy: 1140,
    density: 3.122,
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    discoveredBy: 'Antoine Jérôme Balard',
    yearDiscovered: 1826,
    description: 'Bromine is a reddish-brown liquid at room temperature. It is used in flame retardants and pharmaceuticals.',
    period: 4,
    group: 17,
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: '83.798',
    category: 'Noble Gas',
    electronConfiguration: '[Ar]3d¹⁰4s²4p⁶',
    electronegativity: 0,
    atomicRadius: 116,
    ionizationEnergy: 1351,
    density: 0.003733,
    meltingPoint: -157.36,
    boilingPoint: -153.22,
    discoveredBy: 'William Ramsay and Morris Travers',
    yearDiscovered: 1898,
    description: 'Krypton is a noble gas used in lighting and lasers. It was once used to define the meter.',
    period: 4,
    group: 18,
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicMass: '85.468',
    category: 'Alkali Metal',
    electronConfiguration: '[Kr]5s¹',
    electronegativity: 0.82,
    atomicRadius: 220,
    ionizationEnergy: 403,
    density: 1.532,
    meltingPoint: 39.31,
    boilingPoint: 688,
    discoveredBy: 'Robert Bunsen and Gustav Kirchhoff',
    yearDiscovered: 1861,
    description: 'Rubidium is a very soft, silvery-white metal. It is highly reactive and is used in atomic clocks.',
    period: 5,
    group: 1,
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicMass: '87.62',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[Kr]5s²',
    electronegativity: 0.95,
    atomicRadius: 195,
    ionizationEnergy: 550,
    density: 2.64,
    meltingPoint: 777,
    boilingPoint: 1382,
    discoveredBy: 'William Cruickshank',
    yearDiscovered: 1790,
    description: 'Strontium is a soft, silvery metal that turns yellow in air. It is used in fireworks and nuclear batteries.',
    period: 5,
    group: 2,
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicMass: '88.906',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d¹5s²',
    electronegativity: 1.22,
    atomicRadius: 190,
    ionizationEnergy: 600,
    density: 4.469,
    meltingPoint: 1526,
    boilingPoint: 3345,
    discoveredBy: 'Johan Gadolin',
    yearDiscovered: 1794,
    description: 'Yttrium is a silvery-metallic transition metal. It is used in LED lights and superconductors.',
    period: 5,
    group: 3,
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicMass: '91.224',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d²5s²',
    electronegativity: 1.33,
    atomicRadius: 175,
    ionizationEnergy: 640,
    density: 6.506,
    meltingPoint: 1855,
    boilingPoint: 4409,
    discoveredBy: 'Martin Heinrich Klaproth',
    yearDiscovered: 1789,
    description: 'Zirconium is a strong, silvery metal resistant to corrosion. It is used in nuclear reactors and ceramics.',
    period: 5,
    group: 4,
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicMass: '92.906',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d⁴5s¹',
    electronegativity: 1.6,
    atomicRadius: 164,
    ionizationEnergy: 652,
    density: 8.57,
    meltingPoint: 2477,
    boilingPoint: 4744,
    discoveredBy: 'Charles Hatchett',
    yearDiscovered: 1801,
    description: 'Niobium is a soft, grey, ductile transition metal. It is used in steel alloys and superconductors.',
    period: 5,
    group: 5,
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicMass: '95.95',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d⁵5s¹',
    electronegativity: 2.16,
    atomicRadius: 154,
    ionizationEnergy: 684,
    density: 10.22,
    meltingPoint: 2623,
    boilingPoint: 4639,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1778,
    description: 'Molybdenum is a silvery metal used in steel alloys. It is essential for most living organisms.',
    period: 5,
    group: 6,
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicMass: '98',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d⁵5s²',
    electronegativity: 1.9,
    atomicRadius: 147,
    ionizationEnergy: 702,
    density: 11.5,
    meltingPoint: 2157,
    boilingPoint: 4265,
    discoveredBy: 'Carlo Perrier and Emilio Segrè',
    yearDiscovered: 1937,
    description: 'Technetium was the first artificially produced element. It is used in nuclear medicine.',
    period: 5,
    group: 7,
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicMass: '101.07',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d⁷5s¹',
    electronegativity: 2.2,
    atomicRadius: 146,
    ionizationEnergy: 710,
    density: 12.37,
    meltingPoint: 2334,
    boilingPoint: 4150,
    discoveredBy: 'Karl Ernst Claus',
    yearDiscovered: 1844,
    description: 'Ruthenium is a rare transition metal used in electronics and chemical catalysts.',
    period: 5,
    group: 8,
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicMass: '102.91',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d⁸5s¹',
    electronegativity: 2.28,
    atomicRadius: 142,
    ionizationEnergy: 720,
    density: 12.41,
    meltingPoint: 1964,
    boilingPoint: 3695,
    discoveredBy: 'William Hyde Wollaston',
    yearDiscovered: 1803,
    description: 'Rhodium is a rare, silvery-white metal used in catalytic converters and jewelry.',
    period: 5,
    group: 9,
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicMass: '106.42',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d¹⁰',
    electronegativity: 2.2,
    atomicRadius: 139,
    ionizationEnergy: 804,
    density: 12.02,
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    discoveredBy: 'William Hyde Wollaston',
    yearDiscovered: 1803,
    description: 'Palladium is a precious metal used in catalytic converters and electronics.',
    period: 5,
    group: 10,
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicMass: '107.87',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d¹⁰5s¹',
    electronegativity: 1.93,
    atomicRadius: 144,
    ionizationEnergy: 731,
    density: 10.49,
    meltingPoint: 961.78,
    boilingPoint: 2162,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -3000,
    description: 'Silver is a precious metal known for its luster and electrical conductivity. It has been used in jewelry and currency.',
    period: 5,
    group: 11,
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicMass: '112.41',
    category: 'Transition Metal',
    electronConfiguration: '[Kr]4d¹⁰5s²',
    electronegativity: 1.69,
    atomicRadius: 151,
    ionizationEnergy: 868,
    density: 8.65,
    meltingPoint: 321.07,
    boilingPoint: 767,
    discoveredBy: 'Friedrich Stromeyer',
    yearDiscovered: 1817,
    description: 'Cadmium is a soft, silvery-white metal. It is toxic and used in batteries and solar cells.',
    period: 5,
    group: 12,
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indium',
    atomicMass: '114.82',
    category: 'Post-transition Metal',
    electronConfiguration: '[Kr]4d¹⁰5s²5p¹',
    electronegativity: 1.78,
    atomicRadius: 167,
    ionizationEnergy: 558,
    density: 7.31,
    meltingPoint: 156.6,
    boilingPoint: 2072,
    discoveredBy: 'Ferdinand Reich and Hieronymous Theodor Richter',
    yearDiscovered: 1863,
    description: 'Indium is a soft, silvery metal used in LCD screens and solar panels.',
    period: 5,
    group: 13,
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicMass: '118.71',
    category: 'Post-transition Metal',
    electronConfiguration: '[Kr]4d¹⁰5s²5p²',
    electronegativity: 1.96,
    atomicRadius: 140,
    ionizationEnergy: 709,
    density: 7.287,
    meltingPoint: 231.93,
    boilingPoint: 2602,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -3500,
    description: 'Tin is a silvery metal used in solder and tin plating. It has been used since ancient times.',
    period: 5,
    group: 14,
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicMass: '121.76',
    category: 'Metalloid',
    electronConfiguration: '[Kr]4d¹⁰5s²5p³',
    electronegativity: 2.05,
    atomicRadius: 140,
    ionizationEnergy: 834,
    density: 6.685,
    meltingPoint: 630.63,
    boilingPoint: 1587,
    discoveredBy: 'Known to ancient Egyptians',
    yearDiscovered: -3000,
    description: 'Antimony is a silvery-white metalloid used in flame retardants and alloys.',
    period: 5,
    group: 15,
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicMass: '127.60',
    category: 'Metalloid',
    electronConfiguration: '[Kr]4d¹⁰5s²5p⁴',
    electronegativity: 2.1,
    atomicRadius: 142,
    ionizationEnergy: 869,
    density: 6.232,
    meltingPoint: 449.51,
    boilingPoint: 988,
    discoveredBy: 'Franz-Joseph Müller von Reichenstein',
    yearDiscovered: 1782,
    description: 'Tellurium is a silvery-white metalloid used in solar cells and thermoelectric devices.',
    period: 5,
    group: 16,
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicMass: '126.90',
    category: 'Nonmetal',
    electronConfiguration: '[Kr]4d¹⁰5s²5p⁵',
    electronegativity: 2.66,
    atomicRadius: 140,
    ionizationEnergy: 1008,
    density: 4.93,
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    discoveredBy: 'Bernard Courtois',
    yearDiscovered: 1811,
    description: 'Iodine is a bluish-black solid that sublimes into a purple gas. It is essential for human health.',
    period: 5,
    group: 17,
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicMass: '131.29',
    category: 'Noble Gas',
    electronConfiguration: '[Kr]4d¹⁰5s²5p⁶',
    electronegativity: 0,
    atomicRadius: 136,
    ionizationEnergy: 1170,
    density: 0.005887,
    meltingPoint: -111.8,
    boilingPoint: -108.1,
    discoveredBy: 'William Ramsay and Morris Travers',
    yearDiscovered: 1898,
    description: 'Xenon is a noble gas used in flash lamps and ion thrusters for spacecraft.',
    period: 5,
    group: 18,
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Caesium',
    atomicMass: '132.91',
    category: 'Alkali Metal',
    electronConfiguration: '[Xe]6s¹',
    electronegativity: 0.79,
    atomicRadius: 260,
    ionizationEnergy: 376,
    density: 1.873,
    meltingPoint: 28.44,
    boilingPoint: 671,
    discoveredBy: 'Robert Bunsen and Gustav Kirchhoff',
    yearDiscovered: 1860,
    description: 'Caesium is a soft, silvery-gold alkali metal. It is used in atomic clocks and scientific instruments.',
    period: 6,
    group: 1,
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicMass: '137.33',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[Xe]6s²',
    electronegativity: 0.89,
    atomicRadius: 215,
    ionizationEnergy: 503,
    density: 3.594,
    meltingPoint: 727,
    boilingPoint: 1897,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1774,
    description: 'Barium is a soft, silvery alkaline earth metal. It is used in X-ray imaging and spark plugs.',
    period: 6,
    group: 2,
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicMass: '138.91',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]5d¹6s²',
    electronegativity: 1.1,
    atomicRadius: 195,
    ionizationEnergy: 538,
    density: 6.145,
    meltingPoint: 920,
    boilingPoint: 3464,
    discoveredBy: 'Carl Gustaf Mosander',
    yearDiscovered: 1839,
    description: 'Lanthanum is a soft, silvery metal and the first lanthanide. It is used in optical glass and catalysts.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicMass: '140.12',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹5d¹6s²',
    electronegativity: 1.12,
    atomicRadius: 185,
    ionizationEnergy: 534,
    density: 6.77,
    meltingPoint: 795,
    boilingPoint: 3443,
    discoveredBy: 'Martin Heinrich Klaproth',
    yearDiscovered: 1803,
    description: 'Cerium is the most abundant rare earth element. It is used in catalytic converters and lighter flints.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicMass: '140.91',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f³6s²',
    electronegativity: 1.13,
    atomicRadius: 185,
    ionizationEnergy: 527,
    density: 6.773,
    meltingPoint: 931,
    boilingPoint: 3520,
    discoveredBy: 'Carl Auer von Welsbach',
    yearDiscovered: 1885,
    description: 'Praseodymium is used in magnets and as a green colorant in glass. It forms a distinctive yellow-green oxide.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicMass: '144.24',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁴6s²',
    electronegativity: 1.14,
    atomicRadius: 185,
    ionizationEnergy: 533,
    density: 7.007,
    meltingPoint: 1021,
    boilingPoint: 3074,
    discoveredBy: 'Carl Auer von Welsbach',
    yearDiscovered: 1885,
    description: 'Neodymium is used in powerful permanent magnets and lasers. It gives glass a purple tint.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicMass: '145',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁵6s²',
    electronegativity: 1.13,
    atomicRadius: 185,
    ionizationEnergy: 540,
    density: 7.26,
    meltingPoint: 1042,
    boilingPoint: 3000,
    discoveredBy: 'Jacob A. Marinsky',
    yearDiscovered: 1945,
    description: 'Promethium is a radioactive element that does not occur naturally. It is used in atomic batteries.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicMass: '150.36',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁶6s²',
    electronegativity: 1.17,
    atomicRadius: 185,
    ionizationEnergy: 545,
    density: 7.52,
    meltingPoint: 1074,
    boilingPoint: 1794,
    discoveredBy: 'Paul Émile Lecoq de Boisbaudran',
    yearDiscovered: 1879,
    description: 'Samarium is used in magnets, optical lasers, and nuclear reactors. It has unique magnetic properties.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicMass: '151.96',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁷6s²',
    electronegativity: 1.2,
    atomicRadius: 185,
    ionizationEnergy: 547,
    density: 5.243,
    meltingPoint: 822,
    boilingPoint: 1527,
    discoveredBy: 'Eugène-Anatole Demarçay',
    yearDiscovered: 1901,
    description: 'Europium is used in red phosphors for displays. It is one of the least abundant rare earth elements.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicMass: '157.25',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁷5d¹6s²',
    electronegativity: 1.2,
    atomicRadius: 180,
    ionizationEnergy: 593,
    density: 7.895,
    meltingPoint: 1313,
    boilingPoint: 3273,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    yearDiscovered: 1880,
    description: 'Gadolinium is used in MRI contrast agents and neutron radiography. It has unique magnetic properties.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicMass: '158.93',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f⁹6s²',
    electronegativity: 1.2,
    atomicRadius: 175,
    ionizationEnergy: 566,
    density: 8.229,
    meltingPoint: 1356,
    boilingPoint: 3230,
    discoveredBy: 'Carl Gustaf Mosander',
    yearDiscovered: 1843,
    description: 'Terbium is used in green phosphors and magneto-optical devices. It has a bright, fluorescent green color.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicMass: '162.50',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹⁰6s²',
    electronegativity: 1.22,
    atomicRadius: 175,
    ionizationEnergy: 573,
    density: 8.55,
    meltingPoint: 1412,
    boilingPoint: 2567,
    discoveredBy: 'Paul Émile Lecoq de Boisbaudran',
    yearDiscovered: 1886,
    description: 'Dysprosium is used in permanent magnets and nuclear control rods. Its name means "hard to get" in Greek.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicMass: '164.93',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹¹6s²',
    electronegativity: 1.23,
    atomicRadius: 175,
    ionizationEnergy: 581,
    density: 8.795,
    meltingPoint: 1474,
    boilingPoint: 2700,
    discoveredBy: 'Marc Delafontaine and Jacques-Louis Soret',
    yearDiscovered: 1878,
    description: 'Holmium has the strongest magnetic properties of any element. It is used in nuclear control rods.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicMass: '167.26',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹²6s²',
    electronegativity: 1.24,
    atomicRadius: 175,
    ionizationEnergy: 589,
    density: 9.066,
    meltingPoint: 1497,
    boilingPoint: 2868,
    discoveredBy: 'Carl Gustaf Mosander',
    yearDiscovered: 1843,
    description: 'Erbium is used in fiber optics and as a pink colorant in glass. It has a distinctive pink color.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicMass: '168.93',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹³6s²',
    electronegativity: 1.25,
    atomicRadius: 175,
    ionizationEnergy: 597,
    density: 9.321,
    meltingPoint: 1545,
    boilingPoint: 1950,
    discoveredBy: 'Per Teodor Cleve',
    yearDiscovered: 1879,
    description: 'Thulium is the least abundant naturally occurring lanthanide. It is used in portable X-ray devices.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicMass: '173.05',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹⁴6s²',
    electronegativity: 1.1,
    atomicRadius: 175,
    ionizationEnergy: 603,
    density: 6.965,
    meltingPoint: 819,
    boilingPoint: 1196,
    discoveredBy: 'Jean Charles Galissard de Marignac',
    yearDiscovered: 1878,
    description: 'Ytterbium is used in atomic clocks and fiber optic technology. It has a silvery-white appearance.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicMass: '174.97',
    category: 'Lanthanide',
    electronConfiguration: '[Xe]4f¹⁴5d¹6s²',
    electronegativity: 1.27,
    atomicRadius: 175,
    ionizationEnergy: 524,
    density: 9.84,
    meltingPoint: 1663,
    boilingPoint: 3402,
    discoveredBy: 'Georges Urbain',
    yearDiscovered: 1907,
    description: 'Lutetium is the last lanthanide and the most expensive rare earth element. It is used in catalysts and medical applications.',
    period: 6,
    group: 3,
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicMass: '178.49',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d²6s²',
    electronegativity: 1.3,
    atomicRadius: 155,
    ionizationEnergy: 659,
    density: 13.31,
    meltingPoint: 2233,
    boilingPoint: 4603,
    discoveredBy: 'Dirk Coster and George de Hevesy',
    yearDiscovered: 1923,
    description: 'Hafnium is used in nuclear control rods and superalloys. It is very resistant to corrosion.',
    period: 6,
    group: 4,
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicMass: '180.95',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d³6s²',
    electronegativity: 1.5,
    atomicRadius: 145,
    ionizationEnergy: 761,
    density: 16.654,
    meltingPoint: 3017,
    boilingPoint: 5458,
    discoveredBy: 'Anders Gustaf Ekeberg',
    yearDiscovered: 1802,
    description: 'Tantalum is a rare, hard, blue-gray metal used in surgical instruments and electronics.',
    period: 6,
    group: 5,
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicMass: '183.84',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d⁴6s²',
    electronegativity: 2.36,
    atomicRadius: 135,
    ionizationEnergy: 770,
    density: 19.25,
    meltingPoint: 3422,
    boilingPoint: 5555,
    discoveredBy: 'Carl Wilhelm Scheele',
    yearDiscovered: 1781,
    description: 'Tungsten has the highest melting point of all elements. It is used in light bulb filaments and tools.',
    period: 6,
    group: 6,
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicMass: '186.21',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d⁵6s²',
    electronegativity: 1.9,
    atomicRadius: 135,
    ionizationEnergy: 760,
    density: 21.02,
    meltingPoint: 3186,
    boilingPoint: 5596,
    discoveredBy: 'Walter Noddack, Ida Tacke, and Otto Berg',
    yearDiscovered: 1925,
    description: 'Rhenium is one of the rarest elements in Earth\'s crust. It is used in jet engines and filaments.',
    period: 6,
    group: 7,
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicMass: '190.23',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d⁶6s²',
    electronegativity: 2.2,
    atomicRadius: 130,
    ionizationEnergy: 840,
    density: 22.59,
    meltingPoint: 3033,
    boilingPoint: 5012,
    discoveredBy: 'Smithson Tennant',
    yearDiscovered: 1803,
    description: 'Osmium is the densest naturally occurring element. It is used in electrical contacts and fountain pen tips.',
    period: 6,
    group: 8,
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicMass: '192.22',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d⁷6s²',
    electronegativity: 2.2,
    atomicRadius: 135,
    ionizationEnergy: 880,
    density: 22.56,
    meltingPoint: 2466,
    boilingPoint: 4428,
    discoveredBy: 'Smithson Tennant',
    yearDiscovered: 1803,
    description: 'Iridium is the most corrosion-resistant metal. It is used in spark plugs and crucibles.',
    period: 6,
    group: 9,
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicMass: '195.08',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d⁹6s¹',
    electronegativity: 2.28,
    atomicRadius: 135,
    ionizationEnergy: 870,
    density: 21.45,
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    discoveredBy: 'Antonio de Ulloa',
    yearDiscovered: 1735,
    description: 'Platinum is a precious metal used in jewelry, catalytic converters, and laboratory equipment.',
    period: 6,
    group: 10,
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicMass: '196.97',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s¹',
    electronegativity: 2.54,
    atomicRadius: 135,
    ionizationEnergy: 890,
    density: 19.32,
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -6000,
    description: 'Gold is a precious metal prized for its beauty and resistance to corrosion. It is used in jewelry and electronics.',
    period: 6,
    group: 11,
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicMass: '200.59',
    category: 'Transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²',
    electronegativity: 2.0,
    atomicRadius: 150,
    ionizationEnergy: 1007,
    density: 13.534,
    meltingPoint: -38.83,
    boilingPoint: 356.73,
    discoveredBy: 'Known to ancient Chinese and Indians',
    yearDiscovered: -2000,
    description: 'Mercury is the only metal that is liquid at room temperature. It is used in thermometers and switches.',
    period: 6,
    group: 12,
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicMass: '204.38',
    category: 'Post-transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p¹',
    electronegativity: 1.62,
    atomicRadius: 190,
    ionizationEnergy: 589,
    density: 11.85,
    meltingPoint: 304,
    boilingPoint: 1473,
    discoveredBy: 'William Crookes',
    yearDiscovered: 1861,
    description: 'Thallium is a highly toxic metal. It is used in electronics and medical imaging.',
    period: 6,
    group: 13,
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicMass: '207.2',
    category: 'Post-transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p²',
    electronegativity: 2.33,
    atomicRadius: 180,
    ionizationEnergy: 716,
    density: 11.34,
    meltingPoint: 327.46,
    boilingPoint: 1749,
    discoveredBy: 'Known to prehistoric humans',
    yearDiscovered: -4000,
    description: 'Lead is a heavy metal that has been used since ancient times. It is toxic but used in batteries and radiation shielding.',
    period: 6,
    group: 14,
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicMass: '208.98',
    category: 'Post-transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p³',
    electronegativity: 2.02,
    atomicRadius: 160,
    ionizationEnergy: 703,
    density: 9.78,
    meltingPoint: 271.4,
    boilingPoint: 1564,
    discoveredBy: 'Claude François Geoffroy',
    yearDiscovered: 1753,
    description: 'Bismuth is used in pharmaceuticals and cosmetics. It forms colorful oxide crystals.',
    period: 6,
    group: 15,
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicMass: '209',
    category: 'Post-transition Metal',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p⁴',
    electronegativity: 2.0,
    atomicRadius: 168,
    ionizationEnergy: 812,
    density: 9.196,
    meltingPoint: 254,
    boilingPoint: 962,
    discoveredBy: 'Marie Curie',
    yearDiscovered: 1898,
    description: 'Polonium is a highly radioactive element. It is used in anti-static devices and atomic batteries.',
    period: 6,
    group: 16,
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicMass: '210',
    category: 'Metalloid',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p⁵',
    electronegativity: 2.2,
    atomicRadius: 170,
    ionizationEnergy: 920,
    density: 7,
    meltingPoint: 302,
    boilingPoint: 337,
    discoveredBy: 'Dale R. Corson',
    yearDiscovered: 1940,
    description: 'Astatine is the rarest naturally occurring element. It is highly radioactive and used in research.',
    period: 6,
    group: 17,
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicMass: '222',
    category: 'Noble Gas',
    electronConfiguration: '[Xe]4f¹⁴5d¹⁰6s²6p⁶',
    electronegativity: 0,
    atomicRadius: 120,
    ionizationEnergy: 1037,
    density: 0.00973,
    meltingPoint: -71,
    boilingPoint: -61.7,
    discoveredBy: 'Friedrich Ernst Dorn',
    yearDiscovered: 1900,
    description: 'Radon is a radioactive noble gas. It is a health hazard but used in radiation therapy.',
    period: 6,
    group: 18,
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicMass: '223',
    category: 'Alkali Metal',
    electronConfiguration: '[Rn]7s¹',
    electronegativity: 0.7,
    atomicRadius: 260,
    ionizationEnergy: 380,
    density: 1.87,
    meltingPoint: 27,
    boilingPoint: 677,
    discoveredBy: 'Marguerite Perey',
    yearDiscovered: 1939,
    description: 'Francium is the most unstable naturally occurring element. It is extremely rare and highly radioactive.',
    period: 7,
    group: 1,
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicMass: '226',
    category: 'Alkaline Earth Metal',
    electronConfiguration: '[Rn]7s²',
    electronegativity: 0.9,
    atomicRadius: 215,
    ionizationEnergy: 509,
    density: 5.5,
    meltingPoint: 700,
    boilingPoint: 1737,
    discoveredBy: 'Marie and Pierre Curie',
    yearDiscovered: 1898,
    description: 'Radium is a radioactive metal once used in luminous paint. It is now used in nuclear medicine.',
    period: 7,
    group: 2,
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicMass: '227',
    category: 'Actinide',
    electronConfiguration: '[Rn]6d¹7s²',
    electronegativity: 1.1,
    atomicRadius: 195,
    ionizationEnergy: 499,
    density: 10.07,
    meltingPoint: 1050,
    boilingPoint: 3200,
    discoveredBy: 'André-Louis Debierne',
    yearDiscovered: 1899,
    description: 'Actinium is a highly radioactive metal. It is used in neutron sources and radiation therapy.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicMass: '232.04',
    category: 'Actinide',
    electronConfiguration: '[Rn]6d²7s²',
    electronegativity: 1.3,
    atomicRadius: 180,
    ionizationEnergy: 587,
    density: 11.72,
    meltingPoint: 1842,
    boilingPoint: 4788,
    discoveredBy: 'Jöns Jakob Berzelius',
    yearDiscovered: 1829,
    description: 'Thorium is a radioactive metal used in nuclear fuel. It was once used in gas mantles.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicMass: '231.04',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f²6d¹7s²',
    electronegativity: 1.5,
    atomicRadius: 180,
    ionizationEnergy: 568,
    density: 15.37,
    meltingPoint: 1841,
    boilingPoint: 4300,
    discoveredBy: 'William Crookes',
    yearDiscovered: 1913,
    description: 'Protactinium is a radioactive metal. It is extremely rare and has few uses outside research.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicMass: '238.03',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f³6d¹7s²',
    electronegativity: 1.38,
    atomicRadius: 175,
    ionizationEnergy: 598,
    density: 19.1,
    meltingPoint: 1133,
    boilingPoint: 4131,
    discoveredBy: 'Martin Heinrich Klaproth',
    yearDiscovered: 1789,
    description: 'Uranium is a radioactive metal used in nuclear power and weapons. It is the heaviest naturally occurring element.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicMass: '237',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f⁴6d¹7s²',
    electronegativity: 1.36,
    atomicRadius: 175,
    ionizationEnergy: 605,
    density: 20.45,
    meltingPoint: 644,
    boilingPoint: 4000,
    discoveredBy: 'Edwin McMillan and Philip H. Abelson',
    yearDiscovered: 1940,
    description: 'Neptunium was the first synthetic transuranium element. It is used in neutron detection.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicMass: '244',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f⁶7s²',
    electronegativity: 1.28,
    atomicRadius: 175,
    ionizationEnergy: 585,
    density: 19.84,
    meltingPoint: 640,
    boilingPoint: 3230,
    discoveredBy: 'Glenn T. Seaborg',
    yearDiscovered: 1940,
    description: 'Plutonium is a radioactive metal used in nuclear weapons and power. It is highly toxic.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicMass: '243',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f⁷7s²',
    electronegativity: 1.3,
    atomicRadius: 175,
    ionizationEnergy: 578,
    density: 13.69,
    meltingPoint: 1176,
    boilingPoint: 2011,
    discoveredBy: 'Glenn T. Seaborg',
    yearDiscovered: 1944,
    description: 'Americium is used in smoke detectors and as a portable source of gamma radiation.',
    period: 7,
    group: 3,
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicMass: '247',
    category: 'Actinide',
    electronConfiguration: '[Rn]5f⁷6d¹7s²',
    electronegativity: 1.3,
    atomicRadius: 175,
    ionizationEnergy: 581,
    density: 13.51,
    meltingPoint: 1345,
    boilingPoint: 3110,
    discoveredBy: 'Glenn T. Seaborg',
    yearDiscovered: 1944,
    description: 'Curium is used in radioisotope thermoelectric generators for space missions.',
    period: 7,
    group: 3,
  },
  // Add more elements as needed...
]

interface ElementDetailsProps {
  element: Element
  onClose: () => void
}

function ElementDetails({ element, onClose }: ElementDetailsProps) {
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-start">
            <div>
              <h2 className="text-3xl font-bold text-gray-900">
                {element.name} ({element.symbol})
              </h2>
              <p className="text-lg text-gray-600">Atomic Number: {element.atomicNumber}</p>
            </div>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-500"
            >
              <XMarkIcon className="h-6 w-6" />
            </button>
          </div>
          
          <div className="mt-6 space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <h3 className="font-semibold text-gray-900">Physical Properties</h3>
                <ul className="mt-2 space-y-1 text-sm text-gray-600">
                  <li>Atomic Mass: {element.atomicMass} u</li>
                  <li>Density: {element.density} g/cm³</li>
                  <li>Melting Point: {element.meltingPoint}°C</li>
                  <li>Boiling Point: {element.boilingPoint}°C</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-gray-900">Electronic Properties</h3>
                <ul className="mt-2 space-y-1 text-sm text-gray-600">
                  <li>Electron Configuration: {element.electronConfiguration}</li>
                  <li>Electronegativity: {element.electronegativity}</li>
                  <li>Atomic Radius: {element.atomicRadius} pm</li>
                  <li>Ionization Energy: {element.ionizationEnergy} kJ/mol</li>
                </ul>
              </div>
            </div>
            
            <div>
              <h3 className="font-semibold text-gray-900">Historical Information</h3>
              <ul className="mt-2 space-y-1 text-sm text-gray-600">
                <li>Discovered by: {element.discoveredBy}</li>
                <li>Year discovered: {element.yearDiscovered}</li>
              </ul>
            </div>
            
            <div>
              <h3 className="font-semibold text-gray-900">Description</h3>
              <p className="mt-2 text-sm text-gray-600">{element.description}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

interface ElementCardProps {
  element: Element
  onClick: () => void
}

function ElementCard({ element, onClick }: ElementCardProps) {
  return (
    <button
      onClick={onClick}
      className={`w-full aspect-square p-3 rounded-lg text-left transition-colors ${categories[element.category]} hover:scale-105 transform duration-200 shadow-sm`}
    >
      <div className="text-sm text-gray-600">{element.atomicNumber}</div>
      <div className="text-2xl font-bold mb-1">{element.symbol}</div>
      <div className="text-xs truncate">{element.name}</div>
      <div className="text-xs text-gray-600">{Number(element.atomicMass).toFixed(1)}</div>
    </button>
  )
}

export default function PeriodicTableExplorer() {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedElement, setSelectedElement] = useState<Element | null>(null)

  const filteredElements = elements.filter(element =>
    element.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    element.symbol.toLowerCase().includes(searchQuery.toLowerCase()) ||
    element.atomicNumber.toString().includes(searchQuery)
  )

  // Group elements by period for organized display
  const groupedElements = elements.reduce((acc, element) => {
    const period = element.period
    if (!acc[period]) {
      acc[period] = []
    }
    acc[period][element.group - 1] = element
    return acc
  }, {} as Record<number, (Element | null)[]>)

  // Add lanthanides and actinides in their special rows
  const lanthanides = elements.filter(e => e.atomicNumber >= 58 && e.atomicNumber <= 71)
  const actinides = elements.filter(e => e.atomicNumber >= 90 && e.atomicNumber <= 103)

  return (
    <div className="max-w-7xl mx-auto px-4 py-6">
      {/* Search Section */}
      <div className="mb-8">
        <div className="max-w-md mx-auto">
          <input
            type="text"
            placeholder="Search by element name, symbol, or atomic number..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
          />
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-8">
        {/* Main Periodic Table */}
        <div className="lg:w-3/4">
          {searchQuery ? (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {filteredElements.map((element) => (
                <ElementCard key={element.atomicNumber} element={element} onClick={() => setSelectedElement(element)} />
              ))}
            </div>
          ) : (
            <div className="space-y-8">
              {/* Main Groups */}
              {Object.entries(groupedElements).map(([period, elements]) => (
                <div key={period} className="space-y-2">
                  <h3 className="text-sm font-medium text-gray-500">Period {period}</h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {elements.map((element, index) => 
                      element ? (
                        <ElementCard 
                          key={element.atomicNumber} 
                          element={element} 
                          onClick={() => setSelectedElement(element)} 
                        />
                      ) : null
                    )}
                  </div>
                </div>
              ))}

              {/* Lanthanides and Actinides */}
              <div className="space-y-8 mt-8">
                <div className="space-y-2">
                  <h3 className="text-sm font-medium text-gray-500">Lanthanides</h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {lanthanides.map(element => (
                      <ElementCard 
                        key={element.atomicNumber} 
                        element={element} 
                        onClick={() => setSelectedElement(element)} 
                      />
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <h3 className="text-sm font-medium text-gray-500">Actinides</h3>
                  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                    {actinides.map(element => (
                      <ElementCard 
                        key={element.atomicNumber} 
                        element={element} 
                        onClick={() => setSelectedElement(element)} 
                      />
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Sidebar for Ads or Additional Content */}
        <div className="lg:w-1/4 bg-gray-50 rounded-lg p-4">
          <div className="sticky top-4">
            <div className="h-[600px] flex items-center justify-center border-2 border-dashed border-gray-300 rounded-lg">
              <p className="text-gray-400">Ad Space</p>
            </div>
          </div>
        </div>
      </div>

      {selectedElement && (
        <ElementDetails
          element={selectedElement}
          onClose={() => setSelectedElement(null)}
        />
      )}
    </div>
  )
} 